Completed Issue #4 | User Can Add To Cart
ejgilleland/gundam-store pull request #12
Opened 2021-01-23 22:08 UTC by ejgilleland

![image](https://user-images.githubusercontent.com/73370554/105615319-78e0d980-5d84-11eb-9a5d-2db96dccd6a2.png)

2021-01-23 22:12 UTC, uzair-ashraf requested changes

2021-01-23 22:12 UTC, uzair-ashraf commented on main.js
> +
Now that you learned about event delegation, attempt to add one event listener on the product container, and handle your logic from there.

2021-01-23 22:38 UTC, uzair-ashraf requested changes

2021-01-23 22:38 UTC, uzair-ashraf commented on main.js
> +      }
This adds an event listener on each product that is created. Add it in on the product container itself.

Only difference is that you have to iterate through the product list to find the product with the same product id.

You can grab the product id from the card using the closest method and the dataset property

https://developer.mozilla.org/en-US/docs/Web/API/Element/closest
https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/dataset

2021-01-24 02:09 UTC, ejgilleland commented
I added the event listener to the render function now, so I wouldn't need to query the dom to get the main products container again. I hope that's okay!

2021-01-24 10:53 UTC, uzair-ashraf approved these changes

2021-01-26 05:27 UTC, merged